# This is a basic workflow to help you get started with Actions

name: Deploy page

# Controls when the workflow will run
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: page
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        with:
          package_manager: 'yarn'
        id: deploy_to_pages
